name = "meta"
title = "MongoDB Meta Documentation"
intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]
toc_landing_pages = [
    "/style-guide",
    "/writing",
    "/style",
    "/terminology",
    "/terminology/general-term-guidelines",
    "/screenshots",
    "tutorials",
    "reference",
    "/tutorials/screencapture-tool",
]

[constants]
rst = "reStructuredText"
package-branch = "testing"
package-version = "4.4.0"
package-name-org = "mongodb-org"
version = "4.0"
variable-name = "variable value"

[substitutions]
mdbsg = "MongoDB Style Guide"
# code-example-one = "\{+variable-name+\}"
code-example-two = "\\{+variable-name\\+}"
code-example-three = "``{+variable-name+}``"
